### ISSUE TITLE
oeuf => œuf, boeuf => bœuf

### ISSUE THREAD

**Issue by Exirel** [brunobord/typographeur#2]
Ce serait idéal si en prime il était capable de détecter les mots courants (entier) qui sont dans une liste, pour remplacer le classique "oe" par "œ" quand c'est nécessaire.

**Comment by brunobord** [comment]
ce qui est duraille, c'est de trouver une liste exhaustive de ces mots. mais je lâche pas l'affaire.

**Comment by brunobord** [comment]
je tiens un truc, là :

* https://www.dicollecte.org/documentation.php?prj=fr
* https://www.dicollecte.org/download.php?prj=fr
