### ISSUE TITLE
Options to define the HTML tag list you want to skip or not

### ISSUE THREAD

**Issue by brunobord** [brunobord/typographeur#9]
ex:

```sh
typographeur --skip-tags="pre,samp,code,var"
```

this comma-separated list to be splitted into a normal list or tuple to feed the typographeur routine. Then the "normal" tags won't be a shared constant but a variable, with a predefined value.
Will need to take care of the case when you don't set the variable **OR** you don't want any tag to be escaped, which shouldn't lead to the same result.

**Comment by brunobord** [comment]
not sure about it, though... postponing

**Comment by brunobord** [comment]
will be rephrased.

**Comment by dascritch** [comment]
\o/
perhaps combined with a `typographeur --show-default-skip-tags` , as in : 

```bash
typographeur --skip-tags="$(typographeur --show-default-skip-tags),math,tt"
```
